// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHIk_6eTG3mHj6GHMti0MavSWjY-4Pzfk',
    appId: '1:508254151928:web:f4103e3a0156e92073470d',
    messagingSenderId: '508254151928',
    projectId: 'flutterdb-27d4f',
    authDomain: 'flutterdb-27d4f.firebaseapp.com',
    storageBucket: 'flutterdb-27d4f.firebasestorage.app',
    measurementId: 'G-SZCRBT91JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOnxJVYFN52qksgNLfHtEWy9lmzXUBvOM',
    appId: '1:508254151928:android:086bbcd93e3e379173470d',
    messagingSenderId: '508254151928',
    projectId: 'flutterdb-27d4f',
    storageBucket: 'flutterdb-27d4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpd2eL6sudHB-apPqfjybYKj65o0tp0Ec',
    appId: '1:508254151928:ios:5436a299c9d4fee473470d',
    messagingSenderId: '508254151928',
    projectId: 'flutterdb-27d4f',
    storageBucket: 'flutterdb-27d4f.firebasestorage.app',
    iosBundleId: 'com.example.flutterMood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpd2eL6sudHB-apPqfjybYKj65o0tp0Ec',
    appId: '1:508254151928:ios:5436a299c9d4fee473470d',
    messagingSenderId: '508254151928',
    projectId: 'flutterdb-27d4f',
    storageBucket: 'flutterdb-27d4f.firebasestorage.app',
    iosBundleId: 'com.example.flutterMood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHIk_6eTG3mHj6GHMti0MavSWjY-4Pzfk',
    appId: '1:508254151928:web:8e3e0eab2aade6f773470d',
    messagingSenderId: '508254151928',
    projectId: 'flutterdb-27d4f',
    authDomain: 'flutterdb-27d4f.firebaseapp.com',
    storageBucket: 'flutterdb-27d4f.firebasestorage.app',
    measurementId: 'G-VE3JPL1KBQ',
  );

}